### ISSUE TITLE
No episode numbers

### ISSUE THREAD

**Issue by SirJohnDoe** [beralt/horepg#10]
Recently I setup my system again and downloaded the latest version of Horepg. It works well, I run it in cron every morning so I can control at what time it will update the EPG, but I noticed there are no episode numbers for any channel listings.

Is this feature removed? Is it not provided anymore on the Horizon site? Or is the script not functioning properly?

**Comment by beralt** [comment]
I just pushed a fix for this, and tested it locally. Please let me know if this fixes the problem on your side as well.

**Comment by SirJohnDoe** [comment]
Merci! It works just fine now, I'm getting all the episode numbers.
