### ISSUE TITLE
salt & pepper offline :(

### ISSUE THREAD

**Issue by hansworst24** [beralt/horepg#29]
Since today, 17-10-2022, horepgd can't connect any longer to Salt & Pepper :( Does anyone know if there are new URLs available ?

DEBUG:root:Fetching listings for 300 channels
DEBUG:root:Switching hosts due to status code 404 from host web-api-salt.horizon.tv
DEBUG:root:Switching hosts due to status code 404 from host web-api-pepper.horizon.tv
Traceback (most recent call last):
  File "/home/hts/horepg/horepgd.py", line 154, in <module>
    main()
  File "/home/hts/horepg/horepgd.py", line 147, in main
    run_import(channels, args.tvhsocket, args.do_radio_epg, args.nr_days, args.output_path)

**Comment by jbogers** [comment]
Sadly I could not find any replacement URL's yet. I think it's likely that the newer box software is using a different EPG interface/API.

As I don't own a box any more I cannot sniff network traffic to see what other server(s) these are using. For now try using the EPG provided with the DVB-C signal.

**Comment by hansworst24** [comment]
Yeah, I recon as well. Currently back to DVB-C grabber, which works fine, but only max 3 days ahead....

**Comment by beralt** [comment]
It was nice while it lasted. I originally reverse engineered this from the EPG from the TV guide on the Ziggo website. If anything that would be the place to look for the current stuff they use for the EPG.

A few years ago I "cut the cable" and went from DVB-C to IP based TV. Sold my hardware and thus stopped using and maintaining this.

**Comment by hansworst24** [comment]
Well, I appreciated the use of horepg up till the 17th of October '22 :) So thanks for spending time and effort in this 7(?) years ago, it was worth the effort !
