### ISSUE TITLE
Systemd doesn't support an uncontrolled (no pidfile) Daemon with a fork :)

### ISSUE THREAD

**Issue by nberlee** [beralt/horepg#3]
Hi,

I love your script, but either make it a full service (such as http://www.jejik.com/articles/2007/02/a_simple_unix_linux_daemon_in_python/)

or make it an console util which does not exit. 
Both are fine for systemd, in this state there is no supported way for systemd to know that the state is.

**Comment by beralt** [comment]
This was on my todo list. I used to start the script manually, but since the user-base is growing I cannot ignore this issue any longer. And as such I have tried to implement the PID file and provided a systemd service file.
