### ISSUE TITLE
No module requests

### ISSUE THREAD

**Issue by schumi2004** [beralt/horepg#7]
Create Syno package and launched it but it failed on importing module request

root@DS715:/var/packages/HorEPG/scripts# ./start-stop-status start
Starting HorEPG ...
Traceback (most recent call last):
  File "/var/packages/HorEPG/target/horepgd.py", line 17, in <module>
    from tvheadend import *
  File "/volume1/@appstore/HorEPG/tvheadend.py", line 7, in <module>
    import requests
ImportError: No module named 'requests'

I also needed to modify start-stop-status script since it couldn't find horepgd.py
Added variable SYNOPKG_PKGNAME="HorEPG"

**Comment by beralt** [comment]
You need to install the required Python modules, in this specific case the "requests" package which is used to query TVHeadend. You can install this package using pip, which you need to bootstrap first. To do so you need to open a shell and execute:
```
curl -o get-pip.py https://bootstrap.pypa.io/get-pip.py
sudo python3 get-pip.py
sudo python3 -m pip install requests
```
The first line downloads the bootstrap script for pip, the second line executes this script with root-privileges, the third line installs the requests package.

**Comment by schumi2004** [comment]
That's not ideal. Why bootstrap and install modules manually to get a package working. 
This undermines the whole purpose of a package.

**Comment by beralt** [comment]
The previous version of HorEPG used the built-in HTTP client module, and therefore did not depend on any external modules for Python. The implementation of ACL for the TVHeadend interface requires Basic Authentication, which is not covered by the built-in module.

The choice for an external Python package is not that uncommon, and for Python 2 there is a package provided by Synology (called "Python module") which solves this problem for Python 2. There is no such package for Python 3.

I understand that installing pip, and installing additional Python packages is a bit involved. I will look into bundeling requests with the HorEPG package to see if that solves the problem.
